apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  initContainers:
  - name: init-container
    image: curlimages/curl:latest
    command: ['sh', '-c', 'curl -o /usr/share/nginx/html/index.html https://raw.githubusercontent.com/MGamalBehairy/k8s-multi-container-nginx/main/index.html']
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html

  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
    - name: log-volume
      mountPath: /var/log/nginx
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5

  volumes:
  - name: html-volume
    emptyDir: {}
  - name: log-volume
    hostPath:
      path: /mnt/nginx-logs
      type: DirectoryOrCreate

